### ISSUE TITLE
Thanks to the author's hard work, thank the author is willing to disclose the data set.I want to test the accuracy of my model. Can I provide a verification set?

### ISSUE THREAD

**Issue by fusang1337** [gaiasd/DFireDataset#2]
Thanks to the author's hard work, thank the author is willing to disclose the data set!
I download dataset,it contain 4 folds :
`CAD  FP  PublicDataset  WEB`
In your paper, it is said that the test set contains 4306 pictures, but in each folder does not contain 4306*2 pictures, and the number of pictures in the folder does not match (4306+17221) *2 pictures。
So I speculate that you mix the picture inside multiple folders，I want to test the accuracy of my model. Can you provide a test set?

**Comment by pedbrgs** [comment]
Thank you for your interest in our work, @fusang1337! 
You're right. The test images are distributed within these 4 folders (`CAD/`, `FP/`, `PublicDataset/` and `WEB/`).
However, in [this repository](https://mega.nz/folder/q95S2ATb#Bc2jtq6cGsKTWxsDA_6k5Q) are the training and testing sets we used in this paper, including the five folds for cross validation.
I hope it helps you! And please cite our paper in your publications if you use this dataset.
