### ISSUE TITLE
Pre-trained smoke detection models?

### ISSUE THREAD

**Issue by arianaa30** [gaiasd/DFireDataset#5]
Intersting repo. Your sample image shows smoke + fire detection, but there is no pre-trained models available. Can you please share the that model produced that? I'm specifically interested in smoke part.

**Comment by gaiasd** [comment]
We are glad you are interested! In this repository you will find links to [models](https://github.com/pedbrgs/Fire-Detection), but unfortunately we cannot publicly distribute trained weights because of copyrights.

**Comment by arianaa30** [comment]
Thanks but that is only fire and not smoke.

**Comment by pedbrgs** [comment]
@arianaa30 Thank you for your interest in our work. In fact, these models detect fire **and** smoke. The D-Fire dataset includes both classes and the models were trained on it. 

Here is an example of smoke detection from one of our models:

![CADFire005-output](https://github.com/gaiasd/DFireDataset/assets/30960165/5b09587e-bb14-4862-9b0f-4c4e9b38bd18)


You can see more results of these models in our following papers:

- <p align="justify"><b>Pedro Vinícius Almeida Borges de Venâncio</b>, Roger Júnio Campos, Tamires Martins Rezende, Adriano Chaves Lisboa, Adriano Vilela Barbosa: <a href="https://link.springer.com/article/10.1007/s00521-023-08260-2"> A hybrid method for fire detection based on spatial and temporal patterns. </a> In: Neural Computing and Applications, 2023.</p>
- <p align="justify"><b>Pedro Vinícius Almeida Borges de Venâncio</b>, Adriano Chaves Lisboa, Adriano Vilela Barbosa: <a href="https://link.springer.com/article/10.1007/s00521-022-07467-z"> An automatic fire detection system based on deep convolutional neural networks for low-power, resource-constrained devices. </a> In: Neural Computing and Applications, 2022.</p>

**Comment by arianaa30** [comment]
Good. I'll try them to get smoke! I throught they are trained only on the fire images of the Dfire dataset

**Comment by pedbrgs** [comment]
@arianaa30 Excellent! I will close this issue. Any other problem, feel free to open a new issue. If the models and the dataset are useful to you and you want to help us spread the word about our work, please star our repositories. Thank you!

**Comment by arianaa30** [comment]
Hi,
I was trying the models from [the other repo](https://github.com/pedbrgs/Fire-Detection) you mentioned. Does it belong to you?
I have a few questions. Would you be able to answer?

I am running the model with `python3 baseline.py --video ex1.mp4 --model mobilenet`, but it only shows some bash outputs and no output videos. Does it save the output file somewhere? 

```
1/1 [==============================] - 0s 25ms/step
Time taken =  0.04462027549743652
Prediction: non_fire
1/1 [==============================] - 0s 25ms/step
Time taken =  0.043842315673828125
Prediction: non_fire
1/1 [==============================] - 0s 26ms/step
Time taken =  0.04700660705566406
Prediction: non_fire
1/1 [==============================] - 0s 27ms/step
Time taken =  0.050565481185913086
Prediction: non_fire
Results
     video    network  detected  first_frame  time_avg
0  ex1.mp4  mobilenet      True           10  0.049584
```
