### ISSUE TITLE
Regarding data labels

### ISSUE THREAD

**Issue by pramitd** [gaiasd/DFireDataset#6]
Hi,

Thanks for making the dataset public. I also read the Medium post, it looks very promising. 
I just downloaded the dataset, but the labels for both train and test are all blank. Can you confirm if this is a glitch or am I missing something here. 
Looking forward to your reply. 
Best Regards, 
Pramit

**Comment by pedbrgs** [comment]
Hi, @pramitd! Thank you for your interest in our work. Yes, there are examples without bounding boxes. These cases present challenging scenarios, where there are objects that can be confused with fire or smoke. Any questions or problems, feel free to open another issue.
