### ISSUE TITLE
Enhancing D-Fire Dataset's Applicability for Diverse Fire Detection Scenarios

### ISSUE THREAD

**Issue by yihong1120** [gaiasd/DFireDataset#7]
Dear D-Fire Dataset Contributors,

I trust this message finds you in good health and high spirits. I am writing to you today to address a matter of great importance concerning the D-Fire image dataset, which has proven to be an invaluable resource for the development of fire and smoke detection algorithms.

Having delved into the dataset, I have observed its robustness and the meticulous effort that has gone into its curation. However, I believe that there is an opportunity to further enhance its utility by considering the following suggestions:

1. **Diversity in Fire Contexts**: The inclusion of fire images from a wider array of contexts, such as forest fires at different times of the day and urban fires in various architectural settings, could significantly improve the dataset's comprehensiveness.

2. **Varied Lighting Conditions**: Fire and smoke detection in low-light or night-time scenarios can be particularly challenging. Augmenting the dataset with images captured under these conditions would be beneficial for developing more resilient detection models.

3. **Annotation Refinement**: While the current YOLO format annotations are quite useful, providing additional formats such as Pascal VOC or COCO could facilitate the use of the dataset across different object detection frameworks.

4. **Temporal Data Annotation**: For the surveillance videos, annotations that include temporal information could enable the development of models that leverage temporal dynamics for improved detection accuracy.

5. **Live Data Stream Integration**: Establishing a protocol for integrating live data streams from surveillance cameras could pave the way for real-time fire detection and the development of systems that learn continuously from evolving data.

I am keen to hear your thoughts on these propositions and to explore potential collaborations to implement these enhancements. By addressing these aspects, I am confident that we can elevate the D-Fire dataset to new heights, making it even more versatile for researchers and practitioners in the field of fire detection.

Thank you for your time and consideration. I eagerly await your response and am excited about the prospect of contributing to the evolution of the D-Fire dataset.

Best regards,
yihong1120

**Comment by gaiasd** [comment]
Dear @yihong1120,

thank you for your consistent suggestions. We hope to release new improved dataset versions in the future, which hopefully will meet your requirements.

Best regards,

Gaia team
