### ISSUE TITLE
data.yaml file

### ISSUE THREAD

**Issue by bbbts** [gaiasd/DFireDataset#8]
Hi. Does anyone have the data.yaml file for the D-Fire dataset? I'm trying to do object detection using yolov5 and need the data.yaml file for that.

**Comment by gaiasd** [comment]
Hi. It can be generated using the label files already in the dataset. It looks simple to implement a script for that end, but unfortunately we do not have done it.

**Comment by vinay06vinay** [comment]
Hi, It is mentioned that the dataset labels are according to what yolo accepts. but each row of yolo label have 5 columns including classes, but here we do have only one.  I know fire requires only one or two classes only

**Comment by pedbrgs** [comment]
@bbbts Hi! You can access the data file [here](https://github.com/pedbrgs/Fire-Detection/blob/main/data/dfire.yaml). Additionally, I believe all the necessary files for training can also be found in the repository.
